# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        version=$(git ls-remote --tags --sort="v:refname" git://github.com/carcheky/testrepoA.git | tail -n1 | sed 's/.*\///; s/\^{}//')
        git remote add drupalrepo git@github.com:carcheky/testrepoB.git
        git config --global user.email "carcheky@gmail.com"
        git config --global user.name "carcheky"
        git checkout master
        git push -f -u drupalrepo master
        git tag $version
        git push -f -u drupalrepo --tags